### ISSUE TITLE
An unknown server-side error occurred while processing the command.

### ISSUE THREAD

**Issue by FJLopezGarcia** [tombuyse/ionic-appium-protractor-example#1]
HI @tombuyse 
I am having an issue running gulp e2e task. Do you know what could be the reason? A wrong Chrome version installed in the emulator? if this is the case, what is the version you are using?
### NPM log:

``` javascript
.....
.....
BUILD SUCCESSFUL

Total time: 1.841 secs
Built the following apk(s):
    /Users/franciscojlopez/Documents/GitHub/ionic-appium-protractor-example/platforms/android/build/outputs/apk/android-debug.apk


Using the selenium server at http://localhost:4723/wd/hub
[launcher] Running 1 instances of WebDriver
[launcher] Process exited with error code 1


/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:108
  var template = new Error(this.message);
                 ^
UnknownError: An unknown server-side error occurred while processing the command. Original error: An unknown server-side error occurred while processing the command. (Original error: unknown error: Chrome version must be >= 46.0.2490.0
  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Mac OS X 10.10.5 x86_64))
    at new bot.Error (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:108:18)
    at Object.bot.response.checkResponse (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/response.js:109:9)
    at /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:160:24
    at [object Object].promise.Promise.goog.defineClass.invokeCallback_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1337:14)
    at [object Object].promise.ControlFlow.goog.defineClass.goog.defineClass.abort_.error.executeNext_.execute_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2776:14)
    at [object Object].promise.ControlFlow.goog.defineClass.goog.defineClass.abort_.error.executeNext_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2758:21)
    at goog.async.run.processWorkQueue (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/async/run.js:124:15)
    at process._tickCallback (node.js:356:9)
From: Task: WebDriver.createSession()
    at Function.webdriver.WebDriver.acquireSession_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:157:22)
    at Function.webdriver.WebDriver.createSession (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:131:30)
    at [object Object].Builder.build (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/builder.js:445:22)
    at [object Object].DriverProvider.getNewDriver (/usr/local/lib/node_modules/protractor/lib/driverProviders/driverProvider.js:38:7)
    at [object Object].Runner.createBrowser (/usr/local/lib/node_modules/protractor/lib/runner.js:186:37)
    at /usr/local/lib/node_modules/protractor/lib/runner.js:276:21
    at _fulfilled (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:797:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:826:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:759:13)
    at /usr/local/lib/node_modules/protractor/node_modules/q/q.js:525:49
```
### Appium Log

``` javascript
Last login: Thu Apr  7 14:58:10 on ttys004
AMAC02PL1CVG8WN:ionic-appium-protractor-example franciscojlopez$ appium
[Appium] Welcome to Appium v1.5.1
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"android","platformVersion":"5.0","deviceName":"lg g3","browserName":"","autoWebview":true,"app":"/Users/franciscojlopez/Documents/GitHub/ionic-appium-protractor-example/platforms/android/build/outputs/apk/android-debug.apk","count":1}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"android","platformVersion":"5.0","deviceName":"lg g3","browserName":"","autoWebview":true,"app":"/Users/franciscojlopez/Documents...
[Appium] Creating new AndroidDriver session
[Appium] Capabilities:
[Appium]   platformName: 'android'
[Appium]   platformVersion: '5.0'
[Appium]   deviceName: 'lg g3'
[Appium]   browserName: ''
[Appium]   autoWebview: true
[Appium]   app: '/Users/franciscojlopez/Documents/GitHub/ionic-appium-protractor-example/platforms/android/build/outputs/apk/android-debug.apk'
[Appium]   count: 1
[BaseDriver] The following capabilities were provided, but are not recognized by appium: count.
[BaseDriver] Session created with session id: f5aab991-1b5f-4006-a9e0-74b262057a23
[debug] [AndroidDriver] Getting Java version
[AndroidDriver] Java version is: 1.8.0_65
[ADB] Checking whether adb is present
[ADB] Using adb from /Users/franciscojlopez/Documents/Android/SDK/android-sdk-macosx/platform-tools/adb
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[AndroidDriver] Using device: emulator-5554
[ADB] Checking whether adb is present
[ADB] Using adb from /Users/franciscojlopez/Documents/Android/SDK/android-sdk-macosx/platform-tools/adb
[debug] [ADB] Setting device id to emulator-5554
[BaseDriver] Using local app '/Users/franciscojlopez/Documents/GitHub/ionic-appium-protractor-example/platforms/android/build/outputs/apk/android-debug.apk'
[debug] [AndroidDriver] Checking whether app is actually present
[AndroidDriver] Starting Android session
[debug] [ADB] Running /Users/franciscojlopez/Documents/Android/SDK/android-sdk-macosx/platform-tools/adb with args: ["-P",5037,"-s","emulator-5554","wait-for-device"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/franciscojlopez/Documents/Android/SDK/android-sdk-macosx/platform-tools/adb with args: ["-P",5037,"-s","emulator-5554","shell","echo","ping"]
[debug] [Logcat] Starting logcat capture
[debug] [AndroidDriver] Pushing settings apk to device...
[debug] [ADB] Running /Users/franciscojlopez/Documents/Android/SDK/android-sdk-macosx/platform-tools/adb with args: ["-P",5037,"-s","emulator-5554","install","/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/io.appium.settings/bin/settings_apk-debug.apk"]
[debug] [AndroidDriver] Pushing unlock helper app to device...
[debug] [ADB] Running /Users/franciscojlopez/Documents/Android/SDK/android-sdk-macosx/platform-tools/adb with args: ["-P",5037,"-s","emulator-5554","install","/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-unlock/bin/unlock_apk-debug.apk"]
[ADB] Getting device platform version
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/franciscojlopez/Documents/Android/SDK/android-sdk-macosx/platform-tools/adb with args: ["-P",5037,"-s","emulator-5554","shell","getprop","ro.build.version.release"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/franciscojlopez/Documents/Android/SDK/android-sdk-macosx/platform-tools/adb with args: ["-P",5037,"-s","emulator-5554","shell","dumpsys","window"]
[AndroidDriver] Screen already unlocked, doing nothing
[debug] [AndroidDriver] Parsing package and activity from app manifest
[ADB] Checking whether aapt is present
[ADB] Using aapt from /Users/franciscojlopez/Documents/Android/SDK/android-sdk-macosx/build-tools/23.0.2/aapt
[ADB] Extracting package and launch activity from manifest
[debug] [ADB] badging package: com.ionicframework.ionicappiumprotractorexample806497
[debug] [ADB] badging act: com.ionicframework.ionicappiumprotractorexample806497.MainActivity
[debug] [AndroidDriver] Parsed package and activity are: com.ionicframework.ionicappiumprotractorexample806497/com.ionicframework.ionicappiumprotractorexample806497.MainActivity
[AndroidDriver] Remote apk path is /data/local/tmp/73d58248ac93d452f80daa30cf61a202.apk
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/franciscojlopez/Documents/Android/SDK/android-sdk-macosx/platform-tools/adb with args: ["-P",5037,"-s","emulator-5554","shell","ls","/data/local/tmp/73d58248ac93d452f80daa30cf61a202.apk"]
[debug] [AndroidDriver] Checking if app is installed
[debug] [ADB] Getting install status for com.ionicframework.ionicappiumprotractorexample806497
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/franciscojlopez/Documents/Android/SDK/android-sdk-macosx/platform-tools/adb with args: ["-P",5037,"-s","emulator-5554","shell","getprop","ro.build.version.sdk"]
[debug] [ADB] Device API level: 23
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/franciscojlopez/Documents/Android/SDK/android-sdk-macosx/platform-tools/adb with args: ["-P",5037,"-s","emulator-5554","shell","pm","list","packages","-3","com.ionicframework.ionicappiumprotractorexample806497"]
[debug] [ADB] App is  not installed
[AndroidDriver] Apk is not yet installed
[AndroidDriver] installing apk from remote
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/franciscojlopez/Documents/Android/SDK/android-sdk-macosx/platform-tools/adb with args: ["-P",5037,"-s","emulator-5554","shell","mkdir","-p","/data/local/tmp"]
[AndroidDriver] Clearing out any existing remote apks with the same hash
[debug] [AndroidDriver] Removing any old apks
[debug] [AndroidDriver] Except ["73d58248ac93d452f80daa30cf61a202"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/franciscojlopez/Documents/Android/SDK/android-sdk-macosx/platform-tools/adb with args: ["-P",5037,"-s","emulator-5554","shell","ls","/data/local/tmp/*.apk"]
[debug] [ADB] Uninstalling com.ionicframework.ionicappiumprotractorexample806497
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/franciscojlopez/Documents/Android/SDK/android-sdk-macosx/platform-tools/adb with args: ["-P",5037,"-s","emulator-5554","shell","am","force-stop","com.ionicframework.ionicappiumprotractorexample806497"]
[debug] [ADB] Running /Users/franciscojlopez/Documents/Android/SDK/android-sdk-macosx/platform-tools/adb with args: ["-P",5037,"-s","emulator-5554","uninstall","com.ionicframework.ionicappiumprotractorexample806497"]
[ADB] App was not uninstalled, maybe it wasn't on device?
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/franciscojlopez/Documents/Android/SDK/android-sdk-macosx/platform-tools/adb with args: ["-P",5037,"-s","emulator-5554","shell","pm","install","-r","/data/local/tmp/73d58248ac93d452f80daa30cf61a202.apk"]
[debug] [AndroidDriver] Extracting strings from apk /Users/franciscojlopez/Documents/GitHub/ionic-appium-protractor-example/platforms/android/build/outputs/apk/android-debug.apk null /var/folders/1x/0kw8j1jd5mbdvngmkfcpbbnh0000gn/T/com.ionicframework.ionicappiumprotractorexample806497
[debug] [ADB] Extracting strings for language: default
[debug] [ADB] Device API level: 23
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/franciscojlopez/Documents/Android/SDK/android-sdk-macosx/platform-tools/adb with args: ["-P",5037,"-s","emulator-5554","shell","getprop","persist.sys.locale"]
[debug] [ADB] Current device property 'persist.sys.locale': 
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/franciscojlopez/Documents/Android/SDK/android-sdk-macosx/platform-tools/adb with args: ["-P",5037,"-s","emulator-5554","shell","getprop","ro.product.locale"]
[debug] [ADB] Current device property 'ro.product.locale': en-US
[debug] [ADB] No strings.xml for language 'en', getting default strings.xml
[debug] [ADB] Reading strings from converted strings.json
[debug] [ADB] Running /Users/franciscojlopez/Documents/Android/SDK/android-sdk-macosx/platform-tools/adb with args: ["-P",5037,"-s","emulator-5554","push","/var/folders/1x/0kw8j1jd5mbdvngmkfcpbbnh0000gn/T/com.ionicframework.ionicappiumprotractorexample806497/strings.json","/data/local/tmp"]
[debug] [AndroidBootstrap] Watching for bootstrap disconnect
[debug] [ADB] Forwarding system: 4724 to device: 4724
[debug] [ADB] Running /Users/franciscojlopez/Documents/Android/SDK/android-sdk-macosx/platform-tools/adb with args: ["-P",5037,"-s","emulator-5554","forward","tcp:4724","tcp:4724"]
[debug] [UiAutomator] Starting UiAutomator
[debug] [UiAutomator] Moving to state 'starting'
[debug] [UiAutomator] Parsing uiautomator jar
[debug] [UiAutomator] Found jar name: 'AppiumBootstrap.jar'
[debug] [ADB] Running /Users/franciscojlopez/Documents/Android/SDK/android-sdk-macosx/platform-tools/adb with args: ["-P",5037,"-s","emulator-5554","push","/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-android-bootstrap/bootstrap/bin/AppiumBootstrap.jar","/data/local/tmp/"]
[debug] [ADB] Attempting to kill all uiautomator processes
[debug] [ADB] Getting all processes with uiautomator
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/franciscojlopez/Documents/Android/SDK/android-sdk-macosx/platform-tools/adb with args: ["-P",5037,"-s","emulator-5554","shell","ps","uiautomator"]
[ADB] No uiautomator process found to kill, continuing...
[debug] [UiAutomator] Starting UIAutomator
[debug] [ADB] Creating ADB subprocess with args: -P, 5037, -s, emulator-5554, shell, uiautomator, runtest, AppiumBootstrap.jar, -c, io.appium.android.bootstrap.Bootstrap, -e, pkg, com.ionicframework.ionicappiumprotractorexample806497, -e, disableAndroidWatchers, false, -e, acceptSslCerts, false
[debug] [UiAutomator] Moving to state 'online'
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Registered crash watchers.
[AndroidBootstrap] Android bootstrap socket is now connected
[debug] [ADB] Device API level: 23
[debug] [ADB] Getting connected devices...
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Client connected
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/franciscojlopez/Documents/Android/SDK/android-sdk-macosx/platform-tools/adb with args: ["-P",5037,"-s","emulator-5554","shell","am","start","-n","com.ionicframework.ionicappiumprotractorexample806497/com.ionicframework.ionicappiumprotractorexample806497.MainActivity","-S","-a","android.intent.action.MAIN","-c","android.intent.category.LAUNCHER","-f","0x10200000"]
[debug] [ADB] Waiting for pkg: 'com.ionicframework.ionicappiumprotractorexample806497' and activity: 'com.ionicframework.ionicappiumprotractorexample806497.MainActivity' to be focused
[debug] [ADB] Possible activities, to be checked: com.ionicframework.ionicappiumprotractorexample806497.MainActivity, .MainActivity, .com.ionicframework.ionicappiumprotractorexample806497.MainActivity
[debug] [ADB] Getting focused package and activity
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/franciscojlopez/Documents/Android/SDK/android-sdk-macosx/platform-tools/adb with args: ["-P",5037,"-s","emulator-5554","shell","dumpsys","window","windows"]
[debug] [ADB] Found package: 'com.ionicframework.ionicappiumprotractorexample806497' and activity: '.MainActivity'
[AndroidDriver] Setting auto webview
[debug] [AndroidDriver] Getting a list of available webviews
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/franciscojlopez/Documents/Android/SDK/android-sdk-macosx/platform-tools/adb with args: ["-P",5037,"-s","emulator-5554","shell","cat","/proc/net/unix"]
[debug] [AndroidDriver] WEBVIEW_7147 mapped to pid 7147
[debug] [AndroidDriver] Getting process name for webview
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/franciscojlopez/Documents/Android/SDK/android-sdk-macosx/platform-tools/adb with args: ["-P",5037,"-s","emulator-5554","shell","ps"]
[debug] [AndroidDriver] Parsed pid: 7147 pkg: com.ionicframework.ionicappiumprotractorexample806497!
[debug] [AndroidDriver] from: u0_a63,7147,1013,1153552,75624,binder_thr,7f5c88f3f647,S,com.ionicframework.ionicappiumprotractorexample806497
[debug] [AndroidDriver] returning process name: com.ionicframework.ionicappiumprotractorexample806497
[debug] [AndroidDriver] Found webviews: ["WEBVIEW_com.ionicframework.ionicappiumprotractorexample806497"]
[debug] [AndroidDriver] Available contexts: ["NATIVE_APP","WEBVIEW_com.ionicframework.ionicappiumprotractorexample806497"]
[debug] [AndroidDriver] Connecting to chrome-backed webview context 'WEBVIEW_com.ionicframework.ionicappiumprotractorexample806497'
[debug] [Chromedriver] Changed state to 'starting'
[Chromedriver] Set chromedriver binary as: /usr/local/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver
[Chromedriver] Killing any old chromedrivers, running: ps -ef | grep /usr/local/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver | grep -v grep |grep -e '--port=9515\(\s.*\)\?$' | awk '{ print $2 }' | xargs kill -15
[Chromedriver] Successfully cleaned up old chromedrivers
[Chromedriver] Spawning chromedriver with: /usr/local/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver --url-base=wd/hub --port=9515 --adb-port=5037
[Chromedriver] [STDOUT] Starting ChromeDriver 2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4) on port 9515
Only local connections are allowed.
[JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9515/wd/hub/status] with no body
[JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"\",\"status\":0,\"value\":{\"build\":{\"version\":\"alpha\"},\"os\":{\"arch\":\"x86_64\",\"name\":\"Mac OS X\",\"version\":\"10.10.5\"}}}"
[JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.ionicframework.ionicappiumprotractorexample806497","androidUseRunningApp":true,"androidDeviceSerial":"emulator-5554"}}}
[JSONWP Proxy] Got response with status 200: {"sessionId":"c684744b622c4493de9b7c832559c04e","status":13,"value":{"message":"unknown error: Chrome version must be >= 46.0.2490.0\n  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28...
[JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.ionicframework.ionicappiumprotractorexample806497","androidUseRunningApp":true,"androidDeviceSerial":"emulator-5554"}}}
[JSONWP Proxy] Got response with status 200: {"sessionId":"ec70e96cc69815ada9f33e75428fc064","status":13,"value":{"message":"unknown error: Chrome version must be >= 46.0.2490.0\n  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28...
[JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.ionicframework.ionicappiumprotractorexample806497","androidUseRunningApp":true,"androidDeviceSerial":"emulator-5554"}}}
[JSONWP Proxy] Got response with status 200: {"sessionId":"55554e04fbcd3498c418f1b84872dc13","status":13,"value":{"message":"unknown error: Chrome version must be >= 46.0.2490.0\n  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28...
[JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.ionicframework.ionicappiumprotractorexample806497","androidUseRunningApp":true,"androidDeviceSerial":"emulator-5554"}}}
[JSONWP Proxy] Got response with status 200: {"sessionId":"0015f58f4a3b62d020680b327c41f7e1","status":13,"value":{"message":"unknown error: Chrome version must be >= 46.0.2490.0\n  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28...
[Chromedriver] Chromedriver exited unexpectedly with code null, signal SIGTERM
[debug] [Chromedriver] Changed state to 'stopped'
[Chromedriver] Error: An unknown server-side error occurred while processing the command. (Original error: unknown error: Chrome version must be >= 46.0.2490.0
  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Mac OS X 10.10.5 x86_64))
    at JWProxy.command$ (lib/proxy.js:139:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /usr/local/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)
 { [Error: An unknown server-side error occurred while processing the command. (Original error: unknown error: Chrome version must be >= 46.0.2490.0
  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Mac OS X 10.10.5 x86_64))]
  status: 13,
  value: { message: 'unknown error: Chrome version must be >= 46.0.2490.0\n  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Mac OS X 10.10.5 x86_64)' },
  httpCode: 200 }
[debug] [AndroidDriver] Shutting down Android driver
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/franciscojlopez/Documents/Android/SDK/android-sdk-macosx/platform-tools/adb with args: ["-P",5037,"-s","emulator-5554","shell","am","force-stop","com.ionicframework.ionicappiumprotractorexample806497"]
[debug] [ADB] Pressing the HOME button
[debug] [ADB] Getting connected devices...
```

**Comment by garyganyang** [comment]
i had the same problem
Original error: unknown error: Chrome version must be >= 46.0.2490.0

**Comment by kiran-meda** [comment]
I am also facing  same issue while running tests in  emulator using appium. Did any one got the solution.
unknown error: Chrome version must be >= 46.0.2490.0\n  (Driver info: chromedriver=2.21.371459

**Comment by captaincole** [comment]
I fixed this issue by using a newer emulator (or an actual device). I used a nexus 5x. With chromedriver you need a specific version of chrome installed, which is directly proportional to the device age, unless you want to install a new apk
